### ISSUE TITLE
way to build riru into a rom directly via aosp build process

### ISSUE THREAD

**Issue by itmayi** [RikkaApps/Riru#237]
is there plan or a way to build riru into a rom as part of the compilation process.it would be great if riru can work without magisk,i think

**Comment by RikkaW** [comment]
If you know how Riru works and is familiar with framework development, this will be very simple. However, I'm curious about why you want this.

**Comment by itmayi** [comment]
yeah,the reason is i do not want magisk to modify my phone's boot partition, and i'm reading the code and trying to strip the code related about magisk in it. what confuse me is the ro.dalvik.vm.native.bridge is reset to 0 after boot ? (after installation, getprop cmd return 0)

**Comment by RikkaW** [comment]
> what confuse me is the ro.dalvik.vm.native.bridge is reset to 0 after boot ? (after installation, getprop cmd return 0)

It is reset after the system server is started (this part is done in "rirud" and "rirud_java"), or anyone can simply detect Riru by checking this prop.

-------

What Riru do in short:
1. Modify `ro.dalvik.vm.native.bridge` to `libriruloader.so`, so that zygote will "dlopen" it
2. Load modules
3. Manage to "hook" `nativeForkAnd..`and related functions (see jni_hooks.cpp) 
4. Call module functions in `nativeForkAnd..` and related functions

Since you can modify the framework codes, steps 1 and 3 are necessary to you.

What you need to do is:
1. Find somewhere to load the modules
2. Call module functions in "`nativeForkAnd..` functions"(`platform/frameworks/base/core/jni/com_android_internal_os_Zygote.cpp`)
