### ISSUE TITLE
post-fs-data supolicy crashing Riru on SDK 26

### ISSUE THREAD

**Issue by XspeedPL** [RikkaApps/Riru#30]
System crashes without any trace logs as soon as another Magisk module tries to apply those policies (post-fs-data):
```bash
# read configs set in our app
supolicy --live "allow coredomain app_data_file * *"
supolicy --live "attradd {system_app platform_app} mlstrustedsubject"
```

When Riru is disabled the policies are applied successfully.

Boot log: [boot-2019-03-18-14-48-00.log](https://github.com/ElderDrivers/EdXposed/files/2978412/boot-2019-03-18-14-48-00.log)

**Comment by RikkaW** [comment]
Riru's post-fs-data script will run an executable to detect and restart zygote process if necessary (Riru lib not found in zygote memory), maybe this cause "system crash"? But this script should only run once.

List of modules using post-fs-data found from the log. Seems none of these including script you provide.
```
sysconfig-patcher
iYTBP-Vanced-Magisk-Repo
riru-core
riru_edxposed
logcat
```

Can you try if the problem still exists after delete post-fs-data from Riru? And one more thing, why not simply using `logcat > 1.txt` instead of using a logcat module?

**Comment by XspeedPL** [comment]
The source script is this file:
https://github.com/ElderDrivers/EdXposed/blob/master/Core/template_override/common/post-fs-data.sh

I'll try what you said and report later.
I use the log module because it is able to record data before adb daemon starts on the phone.

**Comment by XspeedPL** [comment]
Ok, commenting out the zygote restarter thingy in Riru `post-fs-data.sh` worked perfectly.
All modules (Magisk and Riru) now loaded correctly, there were no restarts, and also the system feels more stable (no more crashing background apps).

**Comment by XspeedPL** [comment]
Status update

After few Magisk module upgrades Riru stopped working. Without the zygote restarter it simply isn't being loaded and with it my device bootloops.

For the time being I set SELinux to permissive instead of patching the policies, until a better alternative is available.

**Comment by XspeedPL** [comment]
New pre-init sepolicy patching support solved the problem.
